<script lang="ts">
  import { onMount } from 'svelte';
  import { page } from '$app/state';
  import { goto } from '$app/navigation';
  import { createPaymentOrder, reviewOrder, type OrderReview, type ShippingMethod } from '$lib/api/order-api';
  let review = $state<OrderReview | null>(null); let isLoading = $state(true); let isSaving = $state(false); let errorMessage = $state(''); let selectedMethod = $state<ShippingMethod>('PICKUP'); let recipientName = $state(''); let phone = $state(''); let address = $state('');
  onMount(async () => { try { const id = page.params.cartItemId; if (!id) throw new Error('Item keranjang tidak ditemukan.'); review = await reviewOrder(Number(id)); recipientName = review.shipping_address.recipient_name; phone = review.shipping_address.phone_number; address = review.shipping_address.address; } catch (error: any) { errorMessage = error.message || 'Gagal memuat checkout.'; } finally { isLoading = false; } });
  function price(value: number) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value); }
  async function submit(event: SubmitEvent) { event.preventDefault(); if (!review) return; isSaving = true; errorMessage = ''; try { const result = await createPaymentOrder(review.item.cart_item_id, { recipient_name: recipientName.trim(), recipient_phone_number: phone.trim(), recipient_address: address.trim(), shipping_method: selectedMethod }); if (result.bookedOrderId) { await goto('/pre-order'); return; } if (!result.orderId) throw new Error('Order tidak berhasil dibuat.'); if (result.paymentURL) { window.open(result.paymentURL, '_blank', 'noopener,noreferrer'); } await goto(`/pesanan/${result.orderId}`); } catch (error: any) { errorMessage = error.message || 'Gagal membuat pesanan.'; } finally { isSaving = false; } }
</script>
<svelte:head><title>Checkout | Tani Siaga</title></svelte:head>
<div class="page-shell"><div class="page-container"><a class="back" href="/keranjang">← Kembali ke keranjang</a>{#if isLoading}<div class="state">Memuat checkout...</div>{:else if errorMessage && !review}<div class="state error">{errorMessage}</div>{:else if review}<div class="heading"><div><p class="eyebrow">CHECKOUT</p><h1>Konfirmasi pesanan</h1><p class="subtitle">Isi informasi penerima dan pilih cara pengiriman sebelum membuat pesanan.</p></div></div>{#if errorMessage}<div class="notice error">{errorMessage}</div>{/if}<div class="checkout-layout"><form class="form-card" onsubmit={submit}><div class="form-section"><p class="eyebrow">INFORMASI PENERIMA</p><label>Nama penerima<input bind:value={recipientName} required /></label><label>Nomor WhatsApp / telepon<input type="tel" bind:value={phone} required /></label><label>Alamat penerima<input bind:value={address} required placeholder="Alamat lengkap atau titik pengambilan" /></label></div><div class="form-section"><p class="eyebrow">METODE PENGIRIMAN</p><div class="method-grid"><label class:chosen={selectedMethod === 'PICKUP'}><input type="radio" bind:group={selectedMethod} value="PICKUP" /> <strong>Pickup</strong><span>Ambil atau sepakati serah terima dengan petani.</span></label><label class:chosen={selectedMethod === 'DIRECT_CONTACT'}><input type="radio" bind:group={selectedMethod} value="DIRECT_CONTACT" /> <strong>Hubungi petani</strong><span>Transaksi di luar platform melalui WhatsApp. Tidak diproses Midtrans.</span></label></div></div><button class="submit" type="submit" disabled={isSaving}>{isSaving ? 'Membuat pesanan...' : selectedMethod === 'PICKUP' ? 'Buat pesanan & lanjut bayar' : 'Buat pesanan langsung'}</button></form><aside class="summary"><p class="eyebrow">RINGKASAN PRODUK</p><div class="product"><strong>{review.item.name}</strong><span>{review.item.quantity} × {price(review.item.price)}</span></div><div class="total"><span>Total</span><strong>{price(review.total_pembayaran)}</strong></div><p class="note">{selectedMethod === 'PICKUP' ? 'Setelah pesanan dibuat, pembayaran dilakukan melalui Midtrans pada tab baru.' : 'Pesanan langsung dianggap selesai. Detail kontak petani tersedia di halaman order.'}</p></aside></div>{/if}</div></div>
<style>
  .page-shell{min-height:100vh;background:#f5f7f0;color:#183126;padding:38px 20px 70px}.page-container{max-width:1000px;margin:auto}.back{display:inline-block;margin-bottom:28px;color:#39754b;font-size:13px;font-weight:700;text-decoration:none}.heading{margin-bottom:28px}.eyebrow{margin:0 0 9px;color:#4e805a;font-size:11px;font-weight:800;letter-spacing:.15em}.heading h1{margin:0;font:600 clamp(40px,6vw,65px)/1 'Fraunces',Georgia,serif}.subtitle{color:#718077}.checkout-layout{display:grid;grid-template-columns:1fr 300px;gap:20px}.form-card,.summary{border:1px solid #d6e1d5;border-radius:10px;background:#fff;padding:24px}.form-card{display:grid;gap:25px}.form-section{display:grid;gap:15px}.form-section>.eyebrow{border-bottom:1px solid #e8eee6;padding-bottom:12px;margin:0}label{display:grid;gap:7px;color:#385540;font-size:12px;font-weight:700}input:not([type=radio]){box-sizing:border-box;width:100%;border:1px solid #d6e1d5;border-radius:7px;background:#fbfdfb;padding:12px;font:inherit;color:#183126;outline:0}input:focus{border-color:#39754b;box-shadow:0 0 0 3px #39754b1c}.method-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.method-grid label{display:grid;grid-template-columns:auto 1fr;gap:5px 8px;padding:15px;border:1px solid #d6e1d5;border-radius:8px;cursor:pointer}.method-grid label.chosen{border-color:#39754b;background:#f4faf2;box-shadow:inset 0 0 0 1px #39754b}.method-grid span{grid-column:2;color:#718077;font-size:11px;font-weight:400;line-height:1.45}.submit{border:0;border-radius:7px;background:#39754b;color:#fff;padding:14px;font:700 13px 'DM Sans',sans-serif;cursor:pointer}.submit:disabled{opacity:.6}.summary{height:max-content}.product{display:flex;justify-content:space-between;gap:15px;padding:18px 0;border-top:1px solid #e8eee6;border-bottom:1px solid #e8eee6}.product strong{font-size:15px}.product span{color:#718077;font-size:12px}.total{display:flex;justify-content:space-between;padding-top:15px}.total span{color:#718077;font-size:12px}.total strong{color:#39754b;font-size:16px}.note{color:#718077;font-size:11px;line-height:1.5}.notice,.state{padding:14px;border:1px solid #d6e1d5;border-radius:8px;background:#fff}.notice.error,.state.error{color:#a44242;background:#fff0ef}.state{text-align:center;color:#718077}@media(max-width:700px){.checkout-layout{grid-template-columns:1fr}.method-grid{grid-template-columns:1fr}}
</style>
